---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      Similar code:
        enabled: false
# ... CONFIG CONTENT ...
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
